import type { Prompt as PromptType, UserProfile } from './types';

export type Prompt = PromptType;

export type Creator = UserProfile;

export type FilterOption = {
  id: string;
  name: string;
};

export const DUMMY_PROMPTS: Prompt[] = [
  {
    id: '1',
    authorId: '1',
    title: 'Cyberpunk Cityscape',
    description: 'A highly detailed prompt for creating futuristic cyberpunk cityscapes with neon-lit streets and flying vehicles.',
    price: 4.99,
    images: ['prompt-1-img'],
    rating: { average: 4.8, count: 124 },
    tags: ['cyberpunk', 'cityscape', 'sci-fi'],
    categories: ['Midjourney'],
    stats: { views: 12500, sales: 312, likes: 2300 },
  },
  {
    id: '2',
    authorId: '2',
    title: 'Enchanted Forest Creatures',
    description: 'Create magical and whimsical creatures that inhabit an ancient, enchanted forest. Perfect for fantasy illustrations.',
    price: 2.99,
    images: ['prompt-2-img'],
    rating: { average: 4.9, count: 256 },
    tags: ['fantasy', 'creature', 'forest'],
    categories: ['Stable Diffusion'],
    stats: { views: 22100, sales: 540, likes: 4100 },
  },
  {
    id: '3',
    authorId: '3',
    title: 'Photorealistic Portraits',
    description: 'A prompt set designed to generate stunningly realistic portraits with natural lighting and emotional depth.',
    price: 9.99,
    images: ['prompt-3-img'],
    rating: { average: 4.7, count: 88 },
    tags: ['portrait', 'photorealistic', 'human'],
    categories: ['FLUX'],
    stats: { views: 8900, sales: 120, likes: 980 },
  },
  {
    id: '4',
    authorId: '1',
    title: 'Vintage Anime Style',
    description: 'Recreate the classic 90s anime aesthetic with this prompt, featuring distinct cell shading and retro color palettes.',
    price: 0,
    images: ['prompt-4-img'],
    rating: { average: 4.6, count: 312 },
    tags: ['anime', 'vintage', '90s'],
    categories: ['ChatGPT Image'],
    stats: { views: 35200, sales: 0, likes: 6200 },
  },
  {
    id: '5',
    authorId: '4',
    title: 'Abstract Fluid Dynamics',
    description: 'Generate beautiful and complex abstract images resembling fluid and smoke dynamics. Ideal for wallpapers and art prints.',
    price: 1.99,
    images: ['prompt-5-img'],
    rating: { average: 4.8, count: 95 },
    tags: ['abstract', 'fluid', 'art'],
    categories: ['Midjourney'],
    stats: { views: 7600, sales: 88, likes: 1100 },
  },
  {
    id: '6',
    authorId: '2',
    title: 'Steampunk Inventions',
    description: 'Design intricate and imaginative steampunk contraptions and inventions, full of gears, cogs, and polished brass.',
    price: 3.49,
    images: ['prompt-6-img'],
    rating: { average: 4.7, count: 150 },
    tags: ['steampunk', 'invention', 'mechanical'],
    categories: ['SDXL'],
    stats: { views: 18400, sales: 250, likes: 2900 },
  },
  {
    id: '7',
    authorId: '3',
    title: 'Gothic Cathedral Interior',
    description: 'A prompt for generating dark, moody, and atmospheric interiors of gothic cathedrals with high contrast lighting.',
    price: 3.99,
    images: ['prompt-7-img'],
    rating: { average: 4.8, count: 180 },
    tags: ['gothic', 'architecture', 'interior'],
    categories: ['Midjourney'],
    stats: { views: 9800, sales: 150, likes: 1500 },
  },
  {
    id: '8',
    authorId: '4',
    title: 'Watercolor Mountain Sunrise',
    description: 'Soft and vibrant watercolor landscapes of mountain ranges at sunrise. Captures the delicate morning light.',
    price: 1.99,
    images: ['prompt-8-img'],
    rating: { average: 4.9, count: 210 },
    tags: ['watercolor', 'landscape', 'mountains'],
    categories: ['Stable Diffusion'],
    stats: { views: 15000, sales: 300, likes: 3200 },
  },
  {
    id: '9',
    authorId: '5',
    title: 'Minimalist Tech Logo',
    description: 'Generate clean, modern, and memorable logos for tech startups and brands. Focuses on simplicity and geometric shapes.',
    price: 7.99,
    images: ['prompt-9-img'],
    rating: { average: 4.7, count: 90 },
    tags: ['logo', 'minimalist', 'tech'],
    categories: ['ChatGPT Image'],
    stats: { views: 11000, sales: 180, likes: 950 },
  },
  {
    id: '10',
    authorId: '1',
    title: 'Detailed Sci-Fi Robot',
    description: 'Create highly-detailed and complex sci-fi robots. Perfect for concept art and character design.',
    price: 5.99,
    images: ['prompt-10-img'],
    rating: { average: 4.8, count: 250 },
    tags: ['robot', 'sci-fi', 'concept art'],
    categories: ['FLUX'],
    stats: { views: 25000, sales: 450, likes: 4500 },
  },
  {
    id: '11',
    authorId: '2',
    title: 'Vibrant Food Photography',
    description: 'A prompt for generating delicious and professional-looking food photography. Great for menus and blogs.',
    price: 2.49,
    images: ['prompt-11-img'],
    rating: { average: 4.6, count: 120 },
    tags: ['food', 'photography', 'vibrant'],
    categories: ['Stable Diffusion'],
    stats: { views: 8000, sales: 110, likes: 1200 },
  },
  {
    id: '12',
    authorId: '3',
    title: 'Cozy Isometric Room',
    description: 'Design cute and cozy isometric rooms filled with plants, books, and other charming details.',
    price: 3.99,
    images: ['prompt-12-img'],
    rating: { average: 4.9, count: 350 },
    tags: ['isometric', 'room', 'cozy'],
    categories: ['Midjourney'],
    stats: { views: 32000, sales: 600, likes: 5500 },
  },
  {
    id: '13',
    authorId: '4',
    title: 'Tropical Seamless Patterns',
    description: 'Generate beautiful and seamless patterns with tropical leaves, flowers, and fruits. Perfect for fabrics and wallpapers.',
    price: 0,
    images: ['prompt-13-img'],
    rating: { average: 4.7, count: 180 },
    tags: ['pattern', 'tropical', 'seamless'],
    categories: ['ChatGPT Image'],
    stats: { views: 19000, sales: 0, likes: 2800 },
  },
  {
    id: '14',
    authorId: '5',
    title: 'Low-Poly Floating Island',
    description: 'A prompt for creating stylish low-poly landscapes of floating islands. Great for game assets or posters.',
    price: 2.99,
    images: ['prompt-14-img'],
    rating: { average: 4.8, count: 200 },
    tags: ['low-poly', 'landscape', 'island'],
    categories: ['FLUX'],
    stats: { views: 14000, sales: 220, likes: 2100 },
  },
  {
    id: '15',
    authorId: '1',
    title: 'Friendly Monster Character',
    description: 'Create a variety of cute and friendly monster characters. Perfect for children\'s books and animations.',
    price: 4.99,
    images: ['prompt-15-img'],
    rating: { average: 4.9, count: 400 },
    tags: ['character', 'monster', 'cute'],
    categories: ['Midjourney'],
    stats: { views: 45000, sales: 900, likes: 8000 },
  },
  {
    id: '16',
    authorId: '2',
    title: 'Surreal Dream Landscape',
    description: 'Generate weird and wonderful surreal landscapes that look like they came from a dream.',
    price: 3.49,
    images: ['prompt-16-img'],
    rating: { average: 4.7, count: 130 },
    tags: ['surreal', 'landscape', 'dream'],
    categories: ['Stable Diffusion'],
    stats: { views: 16000, sales: 210, likes: 2300 },
  },
  {
    id: '17',
    authorId: '3',
    title: 'Colorful Space Nebula',
    description: 'A prompt for creating breathtaking images of colorful space nebulas and galaxies. Looks great on a big screen.',
    price: 0.99,
    images: ['prompt-17-img'],
    rating: { average: 4.8, count: 500 },
    tags: ['space', 'nebula', 'galaxy'],
    categories: ['SDXL'],
    stats: { views: 50000, sales: 1200, likes: 9500 },
  },
  {
    id: '18',
    authorId: '4',
    title: 'Bustling Pixel Art City',
    description: 'Create a detailed and lively pixel art scene of a city, complete with tiny cars and people.',
    price: 6.99,
    images: ['prompt-18-img'],
    rating: { average: 4.9, count: 220 },
    tags: ['pixel art', 'city', '8-bit'],
    categories: ['Aseprite'],
    stats: { views: 28000, sales: 480, likes: 4900 },
  },
  {
    id: '19',
    authorId: '5',
    title: 'Old World Fantasy Map',
    description: 'Generate intricate fantasy maps in the style of old cartography, with mountains, forests, and cities.',
    price: 4.99,
    images: ['prompt-19-img'],
    rating: { average: 4.8, count: 190 },
    tags: ['map', 'fantasy', 'cartography'],
    categories: ['Midjourney'],
    stats: { views: 22000, sales: 350, likes: 3800 },
  },
  {
    id: '20',
    authorId: '1',
    title: 'Sleek Product Mockups',
    description: 'Create professional and realistic mockups for your products, from cosmetics to tech gadgets.',
    price: 8.99,
    images: ['prompt-20-img'],
    rating: { average: 4.7, count: 80 },
    tags: ['mockup', 'product', 'realistic'],
    categories: ['ChatGPT Image'],
    stats: { views: 9500, sales: 130, likes: 850 },
  }
];

export const DUMMY_CREATORS: Creator[] = [
  {
    uid: '1',
    email: 'pixel@forge.com',
    displayName: 'PixelForge',
    photoURL: 'https://picsum.photos/seed/1/40/40',
    role: 'user',
    isSeller: true,
    stats: { totalSales: 56200, monthlySales: 4300, weeklySales: 950, reputation: 99 },
  },
  {
    uid: '2',
    email: 'artisan@ai.com',
    displayName: 'ArtisanAI',
    photoURL: 'https://picsum.photos/seed/2/40/40',
    role: 'user',
    isSeller: true,
    stats: { totalSales: 78000, monthlySales: 5100, weeklySales: 1200, reputation: 98 },
  },
  {
    uid: '3',
    email: 'dream@weaver.com',
    displayName: 'DreamWeaver',
    photoURL: 'https://picsum.photos/seed/3/40/40',
    role: 'user',
    isSeller: true,
    stats: { totalSales: 41500, monthlySales: 3200, weeklySales: 750, reputation: 97 },
  },
  {
    uid: '4',
    email: 'synth@sprite.com',
    displayName: 'SynthSprite',
    photoURL: 'https://picsum.photos/seed/4/40/40',
    role: 'user',
    isSeller: true,
    stats: { totalSales: 25000, monthlySales: 2800, weeklySales: 600, reputation: 95 },
  },
    {
    uid: '5',
    email: 'giga@prompt.com',
    displayName: 'GigaPrompt',
    photoURL: 'https://picsum.photos/seed/5/40/40',
    role: 'user',
    isSeller: true,
    stats: { totalSales: 18500, monthlySales: 1900, weeklySales: 450, reputation: 96 },
  },
];

export const DUMMY_FILTERS = {
  categories: [
    { id: 'sci-fi', name: 'Science Fiction' },
    { id: 'fantasy', name: 'Fantasy' },
    { id: 'characters', name: 'Characters' },
    { id: 'environments', name: 'Environments' },
    { id: 'abstract', name: 'Abstract' },
    { id: 'photorealism', name: 'Photorealism' },
  ],
  models: [
    { id: 'sdxl', name: 'SDXL' },
    { id: 'midjourney-v6', name: 'Midjourney v6' },
    { id: 'dall-e-3', name: 'DALL-E 3' },
    { id: 'stable-diffusion-2', name: 'Stable Diffusion 2.1' },
  ],
};

export const DUMMY_MODELS_AND_STYLES = [
  { id: 'video', name: 'Video' },
  { id: 'chatgpt-image', name: 'ChatGPT Image' },
  { id: 'midjourney', name: 'Midjourney' },
  { id: 'flux', name: 'FLUX' },
  { id: 'sora', name: 'Sora' },
  { id: 'stable-diffusion', name: 'Stable Diffusion' },
  { id: 'portraits', name: 'Portraits' },
  { id: 'photography', name: 'Photography' },
  { id: 'anime', name: 'Anime' },
  { id: 'logo', name: 'Logo' },
  { id: 'character-design', name: 'Character Design' },
];


// This is a helper to find placeholder images from the JSON file
// We are re-exporting it from here for convenience in components
import { PlaceHolderImages } from './placeholder-images';
export const placeholderImages = PlaceHolderImages;
