import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function isFirebaseStorageUrl(url: string | undefined): boolean {
	if (!url) return false
	return (
		url.includes('storage.googleapis.com') ||
		url.includes('firebasestorage.googleapis.com')
	)
}


/**
 * Custom loader for Next/Image that constructs URLs for resized images from Firebase Storage.
 * It intelligently handles multiple Firebase URL formats and directs to the resized image
 * in the 'thumbnails' subdirectory, as generated by the 'Resize Images' extension.
 */
// Flip to true once the Firebase Resize Images extension has produced
// _400x400 / _800x800 / _1200x1200 variants in prompts/thumbnails/ for the
// current bucket. While false, the loader returns originals so Next/Image
// doesn't request thumbnail paths that 404.
const REWRITE_TO_RESIZED_THUMBNAILS = false

export function firebaseImageLoader({
	src,
	width,
}: {
	src: string
	width: number
}): string {
	if (!REWRITE_TO_RESIZED_THUMBNAILS) return src

	if (!isFirebaseStorageUrl(src)) {
		return src
	}

	try {
        const url = new URL(src);
        let bucket = '';
        let path = '';

        // Handle modern format: firebasestorage.googleapis.com/v0/b/{bucket}/o/{path}
        if (url.hostname === 'firebasestorage.googleapis.com') {
            const match = url.pathname.match(/\/v0\/b\/([^/]+)\/o\/(.+)/);
            if (match) {
                bucket = match[1];
                path = decodeURIComponent(match[2]);
            }
        } 
        // Handle legacy format: storage.googleapis.com/{bucket}/{path}
        else if (url.hostname === 'storage.googleapis.com') {
            const parts = url.pathname.split('/').filter(Boolean);
            if (parts.length >= 2) {
                bucket = parts[0];
                path = decodeURIComponent(parts.slice(1).join('/'));
            }
        }

        if (!bucket || !path) {
            console.warn('Could not parse Firebase Storage URL:', src);
            return src;
        }
		
		const lastSlash = path.lastIndexOf('/')
		const directory = lastSlash > -1 ? path.substring(0, lastSlash) : ''
		const filename = path.substring(lastSlash + 1)

		// Avoid re-processing already resized images
		if (directory.includes('/thumbnails')) {
			return src
		}

		const lastDot = filename.lastIndexOf('.')
		const nameWithoutExt = lastDot > -1 ? filename.substring(0, lastDot) : filename
		const extension = lastDot > -1 ? filename.substring(lastDot) : ''

		let sizeSuffix: string
		if (width <= 400) sizeSuffix = '_400x400'
		else if (width <= 800) sizeSuffix = '_800x800'
		else sizeSuffix = '_1200x1200'

		const newFilename = `${nameWithoutExt}${sizeSuffix}${extension}`
		
        const resizedPath = directory
			? `${directory}/thumbnails/${newFilename}`
			: `thumbnails/${newFilename}`

		// Always construct the modern, reliable URL format
		return `https://firebasestorage.googleapis.com/v0/b/${bucket}/o/${encodeURIComponent(
			resizedPath,
		)}?alt=media`
	} catch (error) {
		console.error('firebaseImageLoader error:', error)
		return src // Fallback to original src on any parsing error
	}
}
