'use client'

import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from '@/components/ui/card'
import {
	Dialog,
	DialogContent,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from '@/components/ui/table'
import { useToast } from '@/hooks/use-toast'
import { Loader2, Pencil, PlusCircle, Trash } from 'lucide-react'
import { useEffect, useState } from 'react'

type ModelItem = { id: string; name: string }

export default function AdminModelsPage() {
	const { toast } = useToast()
	const [models, setModels] = useState<ModelItem[]>([])
	const [loading, setLoading] = useState(true)
	const [newName, setNewName] = useState('')
	const [adding, setAdding] = useState(false)
	const [editModel, setEditModel] = useState<ModelItem | null>(null)
	const [editName, setEditName] = useState('')
	const [savingEdit, setSavingEdit] = useState(false)
	const [deleteModel, setDeleteModel] = useState<ModelItem | null>(null)
	const [deleting, setDeleting] = useState(false)

	const fetchModels = async () => {
		setLoading(true)
		try {
			const res = await fetch('/api/models')
			const data = await res.json()
			setModels(Array.isArray(data) ? data : [])
		} catch {
			setModels([])
		} finally {
			setLoading(false)
		}
	}

	useEffect(() => {
		fetchModels()
	}, [])

	const handleCreate = async () => {
		const name = newName.trim()
		if (!name) {
			toast({
				variant: 'destructive',
				title: 'Name required',
				description: 'Enter a model name.',
			})
			return
		}
		setAdding(true)
		try {
			const res = await fetch('/api/models', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ name }),
			})
			const data = await res.json()
			if (!res.ok) throw new Error(data.error || 'Failed to create')
			toast({ title: 'Model created', description: data.name ?? name })
			setNewName('')
			fetchModels()
		} catch (e) {
			toast({
				variant: 'destructive',
				title: 'Error',
				description: e instanceof Error ? e.message : 'Failed to create model.',
			})
		} finally {
			setAdding(false)
		}
	}

	const handleUpdate = async () => {
		if (!editModel) return
		const name = editName.trim()
		if (!name) {
			toast({ variant: 'destructive', title: 'Name required' })
			return
		}
		setSavingEdit(true)
		try {
			const res = await fetch(`/api/models/${editModel.id}`, {
				method: 'PATCH',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ name }),
			})
			const data = await res.json()
			if (!res.ok) throw new Error(data.error || 'Failed to update')
			toast({ title: 'Model updated', description: name })
			setEditModel(null)
			setEditName('')
			fetchModels()
		} catch (e) {
			toast({
				variant: 'destructive',
				title: 'Error',
				description: e instanceof Error ? e.message : 'Failed to update model.',
			})
		} finally {
			setSavingEdit(false)
		}
	}

	const handleDelete = async () => {
		if (!deleteModel) return
		setDeleting(true)
		try {
			const res = await fetch(`/api/models/${deleteModel.id}`, {
				method: 'DELETE',
			})
			const data = await res.json()
			if (!res.ok) throw new Error(data.error || 'Failed to delete')
			toast({ title: 'Model deleted', description: deleteModel.name })
			setDeleteModel(null)
			fetchModels()
		} catch (e) {
			toast({
				variant: 'destructive',
				title: 'Error',
				description: e instanceof Error ? e.message : 'Failed to delete model.',
			})
		} finally {
			setDeleting(false)
		}
	}

	return (
		<div className='space-y-6'>
			<div className='flex items-center justify-between gap-4'>
				<h1 className='text-lg font-semibold md:text-2xl'>Models</h1>
			</div>

			<Card>
				<CardHeader>
					<CardTitle>Add model</CardTitle>
					<CardDescription>
						Create a new model. ID is auto-generated by Firestore.
					</CardDescription>
				</CardHeader>
				<CardContent className='flex flex-wrap items-end gap-4'>
					<div className='space-y-2'>
						<Label htmlFor='new-name'>Name</Label>
						<Input
							id='new-name'
							placeholder='e.g. Gemini'
							value={newName}
							onChange={e => setNewName(e.target.value)}
							disabled={adding}
						/>
					</div>
					<Button onClick={handleCreate} disabled={adding}>
						{adding && <Loader2 className='mr-2 h-4 w-4 animate-spin' />}
						<PlusCircle className='mr-2 h-4 w-4' />
						Add
					</Button>
				</CardContent>
			</Card>

			<Card>
				<CardHeader>
					<CardTitle>All models</CardTitle>
					<CardDescription>
						Edit or delete models. Use POST /api/models (no body) to seed
						defaults.
					</CardDescription>
				</CardHeader>
				<CardContent>
					{loading ? (
						<div className='flex justify-center py-8'>
							<Loader2 className='h-8 w-8 animate-spin text-muted-foreground' />
						</div>
					) : models.length === 0 ? (
						<p className='text-muted-foreground py-4'>
							No models yet. Add one above or seed defaults with: POST /api/models
							(no body).
						</p>
					) : (
						<Table>
							<TableHeader>
								<TableRow>
									<TableHead>ID</TableHead>
									<TableHead>Name</TableHead>
									<TableHead className='w-[120px]'>Actions</TableHead>
								</TableRow>
							</TableHeader>
							<TableBody>
								{models.map(model => (
									<TableRow key={model.id}>
										<TableCell className='font-mono text-sm'>
											{model.id}
										</TableCell>
										<TableCell>{model.name}</TableCell>
										<TableCell>
											<div className='flex gap-2'>
												<Button
													variant='ghost'
													size='icon'
													onClick={() => {
														setEditModel(model)
														setEditName(model.name)
													}}
												>
													<Pencil className='h-4 w-4' />
												</Button>
												<Button
													variant='ghost'
													size='icon'
													className='text-destructive hover:text-destructive'
													onClick={() => setDeleteModel(model)}
												>
													<Trash className='h-4 w-4' />
												</Button>
											</div>
										</TableCell>
									</TableRow>
								))}
							</TableBody>
						</Table>
					)}
				</CardContent>
			</Card>

			<Dialog
				open={!!editModel}
				onOpenChange={open => !open && setEditModel(null)}
			>
				<DialogContent>
					<DialogHeader>
						<DialogTitle>Edit model</DialogTitle>
					</DialogHeader>
					<div className='space-y-2 py-4'>
						<Label>Name</Label>
						<Input
							value={editName}
							onChange={e => setEditName(e.target.value)}
							disabled={savingEdit}
							placeholder='Model name'
						/>
						{editModel && (
							<p className='text-xs text-muted-foreground'>
								ID: {editModel.id} (cannot change)
							</p>
						)}
					</div>
					<DialogFooter>
						<Button
							variant='outline'
							onClick={() => setEditModel(null)}
							disabled={savingEdit}
						>
							Cancel
						</Button>
						<Button onClick={handleUpdate} disabled={savingEdit}>
							{savingEdit && <Loader2 className='mr-2 h-4 w-4 animate-spin' />}
							Save
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>

			<AlertDialog
				open={!!deleteModel}
				onOpenChange={open => !open && setDeleteModel(null)}
			>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>Delete model?</AlertDialogTitle>
						<AlertDialogDescription>
							This will remove &quot;{deleteModel?.name}&quot;. Prompts using
							this model will keep the reference but the name may not resolve
							until you re-add a model with the same ID.
						</AlertDialogDescription>
					</AlertDialogHeader>
					<AlertDialogFooter>
						<AlertDialogCancel disabled={deleting}>Cancel</AlertDialogCancel>
						<AlertDialogAction
							onClick={handleDelete}
							disabled={deleting}
							className='bg-destructive text-destructive-foreground hover:bg-destructive/90'
						>
							{deleting && <Loader2 className='mr-2 h-4 w-4 animate-spin' />}
							Delete
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>
		</div>
	)
}
