'use client'

import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from '@/components/ui/card'
import {
	Dialog,
	DialogContent,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
	Pagination,
	PaginationContent,
	PaginationItem,
	PaginationLink,
	PaginationNext,
	PaginationPrevious,
} from '@/components/ui/pagination'
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select'
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from '@/components/ui/table'
import { useToast } from '@/hooks/use-toast'
import { Loader2, Pencil, PlusCircle, Trash } from 'lucide-react'
import { useEffect, useState } from 'react'

type CategoryItem = { id: string; name: string }

export default function AdminCategoriesPage() {
	const { toast } = useToast()
	const [categories, setCategories] = useState<CategoryItem[]>([])
	const [loading, setLoading] = useState(true)
	const [newName, setNewName] = useState('')
	const [adding, setAdding] = useState(false)
	const [editCategory, setEditCategory] = useState<CategoryItem | null>(null)
	const [editName, setEditName] = useState('')
	const [savingEdit, setSavingEdit] = useState(false)
	const [deleteCategory, setDeleteCategory] = useState<CategoryItem | null>(
		null,
	)
	const [deleting, setDeleting] = useState(false)
	const [itemsPerPage, setItemsPerPage] = useState(10)
	const [currentPage, setCurrentPage] = useState(1)

	const fetchCategories = async () => {
		setLoading(true)
		try {
			const res = await fetch('/api/categories')
			const data = await res.json()
			setCategories(Array.isArray(data) ? data : [])
		} catch {
			setCategories([])
		} finally {
			setLoading(false)
		}
	}

	useEffect(() => {
		fetchCategories()
	}, [])

	const handleCreate = async () => {
		const name = newName.trim()
		if (!name) {
			toast({
				variant: 'destructive',
				title: 'Name required',
				description: 'Enter a category name.',
			})
			return
		}
		setAdding(true)
		try {
			const res = await fetch('/api/categories', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ name }),
			})
			const data = await res.json()
			if (!res.ok) throw new Error(data.error || 'Failed to create')
			toast({ title: 'Category created', description: data.name ?? name })
			setNewName('')
			fetchCategories()
		} catch (e) {
			toast({
				variant: 'destructive',
				title: 'Error',
				description:
					e instanceof Error ? e.message : 'Failed to create category.',
			})
		} finally {
			setAdding(false)
		}
	}

	const handleUpdate = async () => {
		if (!editCategory) return
		const name = editName.trim()
		if (!name) {
			toast({ variant: 'destructive', title: 'Name required' })
			return
		}
		setSavingEdit(true)
		try {
			const res = await fetch(`/api/categories/${editCategory.id}`, {
				method: 'PATCH',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ name }),
			})
			const data = await res.json()
			if (!res.ok) throw new Error(data.error || 'Failed to update')
			toast({ title: 'Category updated', description: name })
			setEditCategory(null)
			setEditName('')
			fetchCategories()
		} catch (e) {
			toast({
				variant: 'destructive',
				title: 'Error',
				description:
					e instanceof Error ? e.message : 'Failed to update category.',
			})
		} finally {
			setSavingEdit(false)
		}
	}

	const handleDelete = async () => {
		if (!deleteCategory) return
		setDeleting(true)
		try {
			const res = await fetch(`/api/categories/${deleteCategory.id}`, {
				method: 'DELETE',
			})
			const data = await res.json()
			if (!res.ok) throw new Error(data.error || 'Failed to delete')
			toast({ title: 'Category deleted', description: deleteCategory.name })
			setDeleteCategory(null)
			fetchCategories()
		} catch (e) {
			toast({
				variant: 'destructive',
				title: 'Error',
				description:
					e instanceof Error ? e.message : 'Failed to delete category.',
			})
		} finally {
			setDeleting(false)
		}
	}

	const pageCount = Math.ceil(categories.length / itemsPerPage)
	const paginatedCategories = categories.slice(
		(currentPage - 1) * itemsPerPage,
		currentPage * itemsPerPage,
	)

	return (
		<div className='space-y-6'>
			<div className='flex items-center justify-between gap-4'>
				<h1 className='text-lg font-semibold md:text-2xl'>Categories</h1>
			</div>

			<Card>
				<CardHeader>
					<CardTitle>Add category</CardTitle>
					<CardDescription>
						Create a new category. ID is auto-generated by Firestore (same
						format as prompt IDs).
					</CardDescription>
				</CardHeader>
				<CardContent className='flex flex-wrap items-end gap-4'>
					<div className='space-y-2'>
						<Label htmlFor='new-name'>Name</Label>
						<Input
							id='new-name'
							placeholder='e.g. Video / Reels'
							value={newName}
							onChange={e => setNewName(e.target.value)}
							disabled={adding}
						/>
					</div>
					<Button onClick={handleCreate} disabled={adding}>
						{adding && <Loader2 className='mr-2 h-4 w-4 animate-spin' />}
						<PlusCircle className='mr-2 h-4 w-4' />
						Add
					</Button>
				</CardContent>
			</Card>

			<Card>
				<CardHeader>
					<div className='flex items-start justify-between gap-4'>
						<div>
							<CardTitle>All categories</CardTitle>
							<CardDescription>
								Edit or delete categories. Used in the prompt dropdown.
							</CardDescription>
						</div>
						<Select
							value={`${itemsPerPage}`}
							onValueChange={value => {
								setItemsPerPage(Number(value))
								setCurrentPage(1)
							}}
						>
							<SelectTrigger className='w-auto gap-2'>
								<SelectValue placeholder='Items per page' />
							</SelectTrigger>
							<SelectContent>
								{[10, 20, 50].map(pageSize => (
									<SelectItem key={pageSize} value={`${pageSize}`}>
										{pageSize} per page
									</SelectItem>
								))}
							</SelectContent>
						</Select>
					</div>
				</CardHeader>
				<CardContent>
					{loading ? (
						<div className='flex justify-center py-8'>
							<Loader2 className='h-8 w-8 animate-spin text-muted-foreground' />
						</div>
					) : paginatedCategories.length === 0 ? (
						<p className='text-muted-foreground py-4'>
							No categories yet. Add one above or seed defaults with: POST
							/api/categories (no body).
						</p>
					) : (
						<Table>
							<TableHeader>
								<TableRow>
									<TableHead>ID</TableHead>
									<TableHead>Name</TableHead>
									<TableHead className='w-[120px]'>Actions</TableHead>
								</TableRow>
							</TableHeader>
							<TableBody>
								{paginatedCategories.map(cat => (
									<TableRow key={cat.id}>
										<TableCell className='font-mono text-sm'>
											{cat.id}
										</TableCell>
										<TableCell>{cat.name}</TableCell>
										<TableCell>
											<div className='flex gap-2'>
												<Button
													variant='ghost'
													size='icon'
													onClick={() => {
														setEditCategory(cat)
														setEditName(cat.name)
													}}
												>
													<Pencil className='h-4 w-4' />
												</Button>
												<Button
													variant='ghost'
													size='icon'
													className='text-destructive hover:text-destructive'
													onClick={() => setDeleteCategory(cat)}
												>
													<Trash className='h-4 w-4' />
												</Button>
											</div>
										</TableCell>
									</TableRow>
								))}
							</TableBody>
						</Table>
					)}
				</CardContent>
				{pageCount > 1 && (
					<CardFooter className='justify-between'>
						<div className='text-sm text-muted-foreground'>
							Page {currentPage} of {pageCount}
						</div>
						<Pagination>
							<PaginationContent>
								<PaginationItem>
									<PaginationPrevious
										onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
										disabled={currentPage === 1}
									/>
								</PaginationItem>
								{Array.from({ length: pageCount }, (_, i) => i + 1).map(
									page => (
										<PaginationItem key={page}>
											<PaginationLink
												onClick={() => setCurrentPage(page)}
												isActive={currentPage === page}
											>
												{page}
											</PaginationLink>
										</PaginationItem>
									),
								)}
								<PaginationItem>
									<PaginationNext
										onClick={() =>
											setCurrentPage(p => Math.min(pageCount, p + 1))
										}
										disabled={currentPage === pageCount}
									/>
								</PaginationItem>
							</PaginationContent>
						</Pagination>
					</CardFooter>
				)}
			</Card>

			<Dialog
				open={!!editCategory}
				onOpenChange={open => !open && setEditCategory(null)}
			>
				<DialogContent>
					<DialogHeader>
						<DialogTitle>Edit category</DialogTitle>
					</DialogHeader>
					<div className='space-y-2 py-4'>
						<Label>Name</Label>
						<Input
							value={editName}
							onChange={e => setEditName(e.target.value)}
							disabled={savingEdit}
							placeholder='Category name'
						/>
						{editCategory && (
							<p className='text-xs text-muted-foreground'>
								ID: {editCategory.id} (cannot change)
							</p>
						)}
					</div>
					<DialogFooter>
						<Button
							variant='outline'
							onClick={() => setEditCategory(null)}
							disabled={savingEdit}
						>
							Cancel
						</Button>
						<Button onClick={handleUpdate} disabled={savingEdit}>
							{savingEdit && <Loader2 className='mr-2 h-4 w-4 animate-spin' />}
							Save
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>

			<AlertDialog
				open={!!deleteCategory}
				onOpenChange={open => !open && setDeleteCategory(null)}
			>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>Delete category?</AlertDialogTitle>
						<AlertDialogDescription>
							This will remove &quot;{deleteCategory?.name}&quot;. Prompts using
							this category will keep the ID but the name may not resolve until
							you re-add a category with the same ID.
						</AlertDialogDescription>
					</AlertDialogHeader>
					<AlertDialogFooter>
						<AlertDialogCancel disabled={deleting}>Cancel</AlertDialogCancel>
						<AlertDialogAction
							onClick={handleDelete}
							disabled={deleting}
							className='bg-destructive text-destructive-foreground hover:bg-destructive/90'
						>
							{deleting && <Loader2 className='mr-2 h-4 w-4 animate-spin' />}
							Delete
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>
		</div>
	)
}